feat(function): enable fetch content from a private repository
hyperjumptech/procheck pull request #4
Opened 2020-12-03 07:38 UTC by dennypradipta

This PR solves #3 which is to handle fetch config from a private repository. In order to do that, we
need one more Github Action parameters called token to insert user Github PAT and add them into the
headers.

BREAKING CHANGE: Existing project that already uses procheck may be breaks because of new params
called token

fix #3

2020-12-05 09:13 UTC, kevinhermawan requested changes

2020-12-05 09:13 UTC, kevin-hyperjump commented on action.yml
> +  token:
Rather than use `token`, I think better to use `githubToken`.

2020-12-05 09:13 UTC, kevin-hyperjump commented on src/main.ts
> +    const token: string = core.getInput('token');
`token` to `githubToken`

2020-12-05 09:13 UTC, kevin-hyperjump commented on src/utils/getConfigs.ts
> +  token: string;
`token` to `githubToken`

2020-12-05 09:13 UTC, kevinhermawan commented on src/utils/getConfigs.ts
> +  const hasToken = token !== '' && {
It's better to write ```const hasToken = token &&``` rather than ```const hasToken =  token !== ''```

2020-12-05 09:13 UTC, kevinhermawan commented on src/utils/getConfigs.ts
> +  const hasToken = token !== '' && {
Since an `undefined` will returns empty when you use ```spread object operator```.

2020-12-06 09:12 UTC, kevinhermawan commented
Looks good to me, but we need to make sure this feature works as expected by adding an integration test for private configs. Please update code-quality.yml to :

```yaml
name: 'Code Quality'
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  analysis-static:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: install dependencies
        run: npm ci

      - name: run static analysis
        run: npm run static:analysis

  test-unit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: install dependencies
        run: npm ci

      - name: run unit test
        run: npm run test:unit

  test-integration:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: install dependencies
        run: npm ci

      - name: build project
        run: npm run build

      - name: package project
        run: npm run package

      - name: test on public configs
      - uses: ./
        with:
          repository: 'hyperjumptech/procheck-configs'
          configPath: 'procheck-integration-test/procheck.json'

      - name: test on private configs
      - uses: ./
        with:
          repository: 'hyperjumptech/procheck-private-configs'
          configPath: 'procheck-integration-test/procheck.json'
          githubToken: $PROCHECK_GITHUB_TOKEN
        env:
          PROCHECK_GITHUB_TOKEN: ${{ secrets.PROCHECK_GITHUB_TOKEN }}
``` 

**Note** : I was created a private repository and `PROCHECK_GITHUB_TOKEN` has been defined.

2020-12-06 09:38 UTC, dennypradipta commented
Thank you for the followups, latest commit should now include test for public and private configs :)

2020-12-08 03:33 UTC, closed without merging